In [1]:
import os
import pandas as pd
import numpy as np

path = r'C:\Mon disque D\Gipsa\6- Schizophrenia diagnosis\dataset'

In [2]:
column_list = pd.read_csv(r"C:\Mon disque D\Gipsa\6- Schizophrenia diagnosis\dataset\dataset 1\columnLabels.csv").columns
print("Column list\n", list(column_list))

channels = column_list[4:-6]
print("Channels\n", list(channels))

demographic = pd.read_csv(r"C:\Mon disque D\Gipsa\6- Schizophrenia diagnosis\dataset\dataset 1\demographic.csv")
diagnosis_dict = dict(zip(demographic.subject, demographic[" group"]))  # 1 SZ 0 CTL
print("Diagnosis dict\n", diagnosis_dict)

df_ERP = pd.read_csv(r'C:\Mon disque D\Gipsa\6- Schizophrenia diagnosis\dataset\dataset 1\ERPdata.csv')
time = df_ERP['time_ms']
df_ERP

Column list
 ['subject', 'trial', 'condition', 'sample', 'Fp1', 'AF7', 'AF3', 'F1', 'F3', 'F5', 'F7', 'FT7', 'FC5', 'FC3', 'FC1', 'C1', 'C3', 'C5', 'T7', 'TP7', 'CP5', 'CP3', 'CP1', 'P1', 'P3', 'P5', 'P7', 'P9', 'PO7', 'PO3', 'O1', 'Iz', 'Oz', 'POz', 'Pz', 'CPz', 'Fpz', 'Fp2', 'AF8', 'AF4', 'AFz', 'Fz', 'F2', 'F4', 'F6', 'F8', 'FT8', 'FC6', 'FC4', 'FC2', 'FCz', 'Cz', 'C2', 'C4', 'C6', 'T8', 'TP8', 'CP6', 'CP4', 'CP2', 'P2', 'P4', 'P6', 'P8', 'P10', 'PO8', 'PO4', 'O2', 'VEOa', 'VEOb', 'HEOL', 'HEOR', 'Nose', 'TP10']
Channels
 ['Fp1', 'AF7', 'AF3', 'F1', 'F3', 'F5', 'F7', 'FT7', 'FC5', 'FC3', 'FC1', 'C1', 'C3', 'C5', 'T7', 'TP7', 'CP5', 'CP3', 'CP1', 'P1', 'P3', 'P5', 'P7', 'P9', 'PO7', 'PO3', 'O1', 'Iz', 'Oz', 'POz', 'Pz', 'CPz', 'Fpz', 'Fp2', 'AF8', 'AF4', 'AFz', 'Fz', 'F2', 'F4', 'F6', 'F8', 'FT8', 'FC6', 'FC4', 'FC2', 'FCz', 'Cz', 'C2', 'C4', 'C6', 'T8', 'TP8', 'CP6', 'CP4', 'CP2', 'P2', 'P4', 'P6', 'P8', 'P10', 'PO8', 'PO4', 'O2']
Diagnosis dict
 {1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 0, 18: 0, 19: 0, 20: 0, 21: 0, 22: 0, 23: 0, 24: 0, 25: 1, 26: 1, 27: 1, 28: 1, 29: 1, 30: 1, 31: 1, 32: 1, 33: 1, 34: 1, 35: 1, 36: 1, 37: 1, 38: 1, 39: 1, 40: 1, 41: 1, 42: 1, 43: 1, 44: 1, 45: 1, 46: 1, 47: 1, 48: 1, 49: 1, 50: 1, 51: 1, 52: 1, 53: 1, 54: 1, 55: 1, 56: 1, 57: 1, 58: 1, 59: 0, 60: 0, 61: 0, 62: 0, 63: 0, 64: 0, 65: 0, 66: 0, 67: 1, 68: 1, 69: 1, 70: 1, 71: 1, 72: 1, 73: 1, 74: 1, 75: 1, 76: 1, 77: 1, 78: 1, 79: 1, 80: 1, 81: 1}

,subject,condition,Fz,FCz,Cz,FC3,FC4,C3,C4,CP3,CP4,time_ms
0,1,1,5.533701,5.726507,5.469535,5.386723,4.588875,6.560092,4.542811,5.397492,5.103695,-1500.0000
1,1,1,5.651489,5.837326,5.773131,5.627975,4.822217,6.739976,4.811770,5.541357,5.379273,-1499.0234
2,1,1,5.717580,5.932924,5.948466,5.826460,4.979647,7.026199,5.053779,5.634972,5.600504,-1498.0469
3,1,1,5.703267,5.968103,5.851512,5.812192,4.992899,6.940671,5.106650,5.543577,5.589775,-1497.0703
4,1,1,5.571578,5.917541,5.812808,5.744715,4.963338,6.726491,5.158073,5.454069,5.614092,-1496.0938
...,...,...,...,...,...,...,...,...,...,...,...,...
746491,81,3,-0.401267,0.041014,-0.352556,0.712530,-0.427019,0.479170,1.041864,0.645761,-0.085649,1495.1172
746492,81,3,-0.440294,0.093863,-0.422151,0.792209,-0.469230,0.486767,0.955658,0.601938,-0.264824,1496.0938
746493,81,3,-0.466162,0.083799,-0.485091,0.799034,-0.466002,0.516740,0.972635,0.612470,-0.463196,1497.0703
746494,81,3,-0.472620,0.003017,-0.465663,0.675452,-0.408777,0.558901,0.943028,0.635287,-0.656748,1498.0469
746495,81,3,-0.496193,0.044210,-0.503998,0.711932,-0.426605,0.672328,0.805889,0.602888,-0.719264,1499.0234

In [3]:
global_df = pd.DataFrame()
for root, dirs, filenames in os.walk(path):
    if dirs:
        continue

    for filename in filenames:
        print(filename)
        df = pd.read_csv(os.path.join(root, filename), header=None, names=column_list)
        df = df.sort_values(by=['condition', 'trial', 'sample'])
        df = df.reset_index(drop=True)
        df = df.groupby(by=['condition', 'sample']).apply('mean')
        df.reset_index(drop=False, inplace=True)
        df.drop('trial', axis=1, inplace=True)
        df = df.astype({'subject': int, 'condition': int, 'sample': int})
        df = df[['subject', 'condition', *channels]]
        df['time_ms'] = time
        global_df = pd.concat([global_df, df], ignore_index=True)

1.csv

In [4]:
global_df.sort_values(by=['subject', 'condition'], inplace=True)
# global_df[global_df.select_dtypes(np.float64).columns] = global_df.select_dtypes(np.float64).astype(np.float32)
# global_df = global_df.astype({'subject': 'int8', 'condition': 'int8'})
global_df

,subject,condition,Fp1,AF7,AF3,F1,F3,F5,F7,FT7,...,CP2,P2,P4,P6,P8,P10,PO8,PO4,O2,time_ms
0,1,1,4.694972,2.070149,3.178188,5.471867,6.226539,4.160494,3.385864,4.273932,...,4.156895,4.918850,5.151279,4.092151,3.090429,1.245846,2.996408,4.748827,3.151972,-1500.0000
1,1,1,4.718298,2.019149,3.247921,5.635916,6.426880,4.441062,3.601036,4.230750,...,4.432032,5.139547,5.393025,4.412252,3.405242,1.611463,3.330815,4.949234,3.429169,-1499.0234
2,1,1,4.612990,2.060838,3.436402,5.843582,6.550092,4.404195,3.641622,4.240790,...,4.740057,5.442154,5.558568,4.609792,3.600952,1.846763,3.413057,5.238907,3.517107,-1498.0469
3,1,1,4.464822,2.209427,3.683950,5.829273,6.435086,4.202639,3.469223,4.102111,...,4.708069,5.435191,5.603686,4.586578,3.571783,1.725657,3.277763,5.178724,3.265150,-1497.0703
4,1,1,4.426163,2.327522,3.621894,5.694745,6.355737,4.028834,3.312064,3.989293,...,4.665796,5.451252,5.619635,4.620001,3.517113,1.637315,3.250003,5.160665,3.175901,-1496.0938
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359419,81,3,-1.767854,0.456810,-0.278523,-0.006992,0.003349,0.010220,-0.016654,0.753018,...,1.319372,0.050155,0.346991,-0.932256,0.128357,-0.154813,0.315715,0.474734,0.863147,1495.1172
359420,81,3,-1.551468,0.523857,-0.293416,-0.009024,0.032590,-0.014151,0.057629,0.778663,...,1.160952,-0.198152,0.060341,-1.191315,-0.136454,-0.338214,0.068372,0.371503,0.673871,1496.0938
359421,81,3,-1.429197,0.551953,-0.231390,-0.032266,0.149262,-0.018225,0.122059,0.847657,...,0.994058,-0.269558,-0.028525,-1.051387,0.062256,-0.330017,0.141756,0.410057,0.682258,1497.0703
359422,81,3,-1.397744,0.588607,-0.265430,-0.117681,0.184459,-0.048643,0.105742,0.897478,...,1.036175,-0.167436,0.020301,-0.842824,0.396513,-0.121367,0.434557,0.575310,0.912079,1498.0469
359423,81,3,-1.365890,0.568882,-0.244426,-0.090889,0.165881,0.094858,0.101904,0.933569,...,1.104176,-0.241988,-0.101359,-0.783718,0.600151,-0.166676,0.535253,0.521306,0.846202,1499.0234

In [8]:
global_df.to_csv(os.path.join(r'C:\Users\meghnouh\PycharmProjects\Schizophrenia Detection\all_chans_ERP.csv'))

In [5]:
gg = global_df[(global_df['subject']==1) & (global_df['condition']==1)]['CPz']

In [7]:
print(gg[0])

4.926734

In [8]:
demographic[' group'].value_counts()

1    49
0    32
Name:  group, dtype: int64