In [8]:
import pandas as pd
import numpy as np

column_list = pd.read_csv(r"C:\Mon disque D\Gipsa\6- Schizophrenia diagnosis\dataset\dataset 1\columnLabels.csv").columns
print("Column list\n", list(column_list))
df = pd.read_csv(r"C:\Mon disque D\Gipsa\6- Schizophrenia diagnosis\dataset\dataset 1\2.csv\2.csv", header=None, names=column_list)
# df = pd.read_csv(r"C:\Mon disque D\Gipsa\6- Schizophrenia diagnosis\dataset\dataset 2\25.csv\25.csv", header=None, names=column_list)

if df.isnull().values.any():
    print("Warning NaN value")
trials_list = list(set(df.trial))

Column list
 ['subject', 'trial', 'condition', 'sample', 'Fp1', 'AF7', 'AF3', 'F1', 'F3', 'F5', 'F7', 'FT7', 'FC5', 'FC3', 'FC1', 'C1', 'C3', 'C5', 'T7', 'TP7', 'CP5', 'CP3', 'CP1', 'P1', 'P3', 'P5', 'P7', 'P9', 'PO7', 'PO3', 'O1', 'Iz', 'Oz', 'POz', 'Pz', 'CPz', 'Fpz', 'Fp2', 'AF8', 'AF4', 'AFz', 'Fz', 'F2', 'F4', 'F6', 'F8', 'FT8', 'FC6', 'FC4', 'FC2', 'FCz', 'Cz', 'C2', 'C4', 'C6', 'T8', 'TP8', 'CP6', 'CP4', 'CP2', 'P2', 'P4', 'P6', 'P8', 'P10', 'PO8', 'PO4', 'O2', 'VEOa', 'VEOb', 'HEOL', 'HEOR', 'Nose', 'TP10']

In [3]:
df

,subject,trial,condition,sample,Fp1,AF7,AF3,F1,F3,F5,...,P10,PO8,PO4,O2,VEOa,VEOb,HEOL,HEOR,Nose,TP10
0,25.0,100.0,1.0,1.0,163.6861,-59.5712,-97.4962,30.9987,109.9633,16.5351,...,-9.0616,9.2542,16.4438,30.9464,121.6653,2.2665,30.2345,99.7302,4.7559,-1.7048
1,25.0,100.0,1.0,2.0,159.1006,-60.2822,-94.5368,31.5271,109.1847,18.0282,...,-12.1559,8.4209,16.3126,30.3871,116.8195,6.0347,32.4924,97.4877,7.1555,-8.4503
2,25.0,100.0,1.0,3.0,155.9969,-56.8593,-90.7525,31.6880,107.4168,20.0397,...,-15.5110,5.6117,14.7600,27.4530,116.3488,7.0529,33.9064,85.6828,7.9614,-13.3521
3,25.0,100.0,1.0,4.0,152.8249,-58.5290,-95.3562,27.5709,102.5454,17.9719,...,-17.0882,3.2644,12.5305,25.4086,105.1124,1.3680,34.9299,59.0185,6.4391,-14.8008
4,25.0,100.0,1.0,5.0,153.2037,-59.6138,-96.9548,26.6000,101.4989,17.6523,...,-18.3553,3.4867,12.2156,25.7534,92.2354,-5.9263,34.4689,40.4010,2.3700,-15.3901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
909307,25.0,9.0,3.0,3068.0,-5.6227,7.9115,-10.4431,-0.8315,-3.7385,-5.5174,...,-0.8136,2.7589,-0.7932,4.7628,-23.4615,-15.3474,-1.6754,-12.5715,-7.0948,-3.6879
909308,25.0,9.0,3.0,3069.0,-7.4910,5.7208,-10.7197,-0.9345,-4.7251,-4.1371,...,0.1677,3.7301,-0.2876,5.4159,-21.2648,-12.6352,-1.1693,-10.4355,-7.0735,-4.3845
909309,25.0,9.0,3.0,3070.0,-7.4572,8.0874,-10.1808,0.2171,-4.7527,-0.6597,...,2.1208,6.4215,2.0231,8.0073,-20.4274,-13.7825,-2.3663,-9.0963,-8.0366,-2.6904
909310,25.0,9.0,3.0,3071.0,-6.0163,13.0608,-9.0206,0.8927,-4.7028,0.8788,...,3.1019,6.7512,1.8637,8.4240,-21.0589,-15.0859,-2.8133,-8.6009,-8.7184,0.7536
909311,25.0,9.0,3.0,3072.0,-7.2617,12.8363,-10.0608,-0.2634,-5.8082,0.1608,...,2.3341,5.2938,0.2187,7.4900,-19.6278,-14.2644,-1.6978,-10.0117,-8.2440,3.3227

In [11]:
df.loc[df['condition'] == 1]['trial'].unique()

array([100.,  10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,
         1.,  20.,  21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,
         2.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,
         3.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,
         4.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,
         5.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,
         6.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,
         7.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,
         8.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
         9.])

In [37]:
df.loc[df['condition'] == 3]['sample'].value_counts()

1.0       100
2.0       100
2043.0    100
2044.0    100
2045.0    100
         ...
1027.0    100
1028.0    100
1029.0    100
1030.0    100
3072.0    100
Name: sample, Length: 3072, dtype: int64

In [38]:
df = pd.read_csv(r"C:\Mon disque D\Gipsa\6- Schizophrenia diagnosis\dataset\dataset 1\ERPdata.csv")

In [68]:
df

,subject,condition,Fz,FCz,Cz,FC3,FC4,C3,C4,CP3,CP4,time_ms
0,1,1,5.533701,5.726507,5.469535,5.386723,4.588875,6.560092,4.542811,5.397492,5.103695,-1500.0000
1,1,1,5.651489,5.837326,5.773131,5.627975,4.822217,6.739976,4.811770,5.541357,5.379273,-1499.0234
2,1,1,5.717580,5.932924,5.948466,5.826460,4.979647,7.026199,5.053779,5.634972,5.600504,-1498.0469
3,1,1,5.703267,5.968103,5.851512,5.812192,4.992899,6.940671,5.106650,5.543577,5.589775,-1497.0703
4,1,1,5.571578,5.917541,5.812808,5.744715,4.963338,6.726491,5.158073,5.454069,5.614092,-1496.0938
...,...,...,...,...,...,...,...,...,...,...,...,...
746491,81,3,-0.401267,0.041014,-0.352556,0.712530,-0.427019,0.479170,1.041864,0.645761,-0.085649,1495.1172
746492,81,3,-0.440294,0.093863,-0.422151,0.792209,-0.469230,0.486767,0.955658,0.601938,-0.264824,1496.0938
746493,81,3,-0.466162,0.083799,-0.485091,0.799034,-0.466002,0.516740,0.972635,0.612470,-0.463196,1497.0703
746494,81,3,-0.472620,0.003017,-0.465663,0.675452,-0.408777,0.558901,0.943028,0.635287,-0.656748,1498.0469
746495,81,3,-0.496193,0.044210,-0.503998,0.711932,-0.426605,0.672328,0.805889,0.602888,-0.719264,1499.0234

In [75]:
fs = 1024
t_min = -0
t_max = 500 - 1/fs
n_point = round((t_max - t_min) / 1000 * fs)
print("n_point:", n_point)
n_channel = 9

for subj in df['subject'].unique():
    data = np.empty((3, n_point, n_channel))
    for stim_i, stim in enumerate(df['condition'].unique()):
        filt = (df['subject'] == subj) & (df['condition'] == stim) & (t_min <= df['time_ms']) & (df['time_ms'] <= t_max)
        data[stim_i, :, :] = df.loc[filt, 'Fz':'CP4']
        print(data[stim_i].shape)

n_point: 512
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)
(512, 9)

In [ ]:
temp_df = data_df.melt(id_vars=['stim', 'subject', 'category', 'parsimony', 'feature'], value_vars=[*channels[0:10]], var_name='channel')
grouped = temp_df.groupby(by=['stim', 'parsimony', 'feature', 'channel'])
tic = time.time()
for stim in tqdm(data_df['stim'].unique()[[0]], position=0, desc='Stim'):
    for channel in tqdm(channels[0:10], position=1, desc='Channel'):
        for pars in parsimony:
            for feature in data_df['feature'].unique():
                data = grouped.get_group((stim, float("{:.2f}".format(pars)), feature, channel))['value'].to_numpy()[:, np.newaxis]
                clf.fit(data, category)
                score = clf.score(data, category)
                if score >= max_acc[0]:
                    max_acc[0] = score
                    print('one feature {:.2f}'.format(max_acc[0] * 100))
print('all time', time.time() - tic)

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\meghnouh\PycharmProjects\Schizophrenia Detection\all_chans_ERP.csv', index_col=[0])

In [3]:
df

,subject,condition,Fp1,AF7,AF3,F1,F3,F5,F7,FT7,...,CP2,P2,P4,P6,P8,P10,PO8,PO4,O2,time_ms
0,1,1,4.694972,2.070149,3.178188,5.471867,6.226539,4.160494,3.385864,4.273932,...,4.156895,4.918850,5.151279,4.092151,3.090429,1.245846,2.996408,4.748827,3.151972,-1500.0000
1,1,1,4.718298,2.019149,3.247921,5.635916,6.426880,4.441062,3.601036,4.230750,...,4.432032,5.139547,5.393025,4.412252,3.405242,1.611463,3.330815,4.949234,3.429169,-1499.0234
2,1,1,4.612990,2.060838,3.436402,5.843582,6.550092,4.404195,3.641622,4.240790,...,4.740057,5.442154,5.558568,4.609792,3.600952,1.846763,3.413057,5.238907,3.517107,-1498.0469
3,1,1,4.464822,2.209427,3.683950,5.829273,6.435086,4.202639,3.469223,4.102111,...,4.708069,5.435191,5.603686,4.586578,3.571783,1.725657,3.277763,5.178724,3.265150,-1497.0703
4,1,1,4.426163,2.327522,3.621894,5.694745,6.355737,4.028834,3.312064,3.989293,...,4.665796,5.451252,5.619635,4.620001,3.517113,1.637315,3.250003,5.160665,3.175901,-1496.0938
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359419,81,3,-1.767854,0.456810,-0.278523,-0.006992,0.003349,0.010220,-0.016654,0.753018,...,1.319372,0.050155,0.346991,-0.932256,0.128357,-0.154813,0.315715,0.474734,0.863147,1495.1172
359420,81,3,-1.551468,0.523857,-0.293416,-0.009024,0.032590,-0.014151,0.057629,0.778663,...,1.160952,-0.198152,0.060341,-1.191315,-0.136454,-0.338214,0.068372,0.371503,0.673871,1496.0938
359421,81,3,-1.429197,0.551953,-0.231390,-0.032266,0.149262,-0.018225,0.122059,0.847657,...,0.994058,-0.269558,-0.028525,-1.051387,0.062256,-0.330017,0.141756,0.410057,0.682258,1497.0703
359422,81,3,-1.397744,0.588607,-0.265430,-0.117681,0.184459,-0.048643,0.105742,0.897478,...,1.036175,-0.167436,0.020301,-0.842824,0.396513,-0.121367,0.434557,0.575310,0.912079,1498.0469
359423,81,3,-1.365890,0.568882,-0.244426,-0.090889,0.165881,0.094858,0.101904,0.933569,...,1.104176,-0.241988,-0.101359,-0.783718,0.600151,-0.166676,0.535253,0.521306,0.846202,1499.0234

In [9]:
gg = df[(df['subject'] == 1) & (df['condition'] == 1)]['Fpz'].to_numpy()
print(gg)

[3.865666 4.028683 4.119934 ... 2.257012 2.410898 2.537495]

In [25]:
df.dtypes

subject         int8
condition       int8
Fp1          float32
AF7          float32
AF3          float32
              ...
P10          float32
PO8          float32
PO4          float32
O2           float32
time_ms      float32
Length: 67, dtype: object

In [24]:
df[df.select_dtypes(np.float64).columns] = df.select_dtypes(np.float64).astype(np.float32)
df = df.astype({'subject': 'int8', 'condition': 'int8'})

In [20]:
df

,subject,condition,Fp1,AF7,AF3,F1,F3,F5,F7,FT7,...,CP2,P2,P4,P6,P8,P10,PO8,PO4,O2,time_ms
0,1,1,4.694972,2.070149,3.178188,5.471867,6.226539,4.160494,3.385864,4.273932,...,4.156895,4.918850,5.151279,4.092151,3.090429,1.245846,2.996408,4.748827,3.151972,-1500.000000
1,1,1,4.718298,2.019149,3.247921,5.635916,6.426880,4.441062,3.601036,4.230750,...,4.432032,5.139547,5.393025,4.412252,3.405242,1.611463,3.330815,4.949234,3.429169,-1499.023438
2,1,1,4.612990,2.060838,3.436402,5.843582,6.550092,4.404195,3.641622,4.240790,...,4.740057,5.442154,5.558568,4.609792,3.600952,1.846763,3.413057,5.238907,3.517107,-1498.046875
3,1,1,4.464822,2.209427,3.683950,5.829273,6.435086,4.202639,3.469223,4.102111,...,4.708069,5.435191,5.603686,4.586578,3.571783,1.725657,3.277763,5.178724,3.265150,-1497.070312
4,1,1,4.426163,2.327522,3.621894,5.694745,6.355737,4.028834,3.312064,3.989293,...,4.665796,5.451252,5.619635,4.620001,3.517113,1.637315,3.250003,5.160665,3.175901,-1496.093750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359419,81,3,-1.767853,0.456810,-0.278523,-0.006992,0.003349,0.010220,-0.016654,0.753018,...,1.319372,0.050155,0.346991,-0.932256,0.128357,-0.154813,0.315715,0.474734,0.863147,1495.117188
359420,81,3,-1.551468,0.523857,-0.293416,-0.009024,0.032590,-0.014151,0.057629,0.778663,...,1.160951,-0.198152,0.060341,-1.191315,-0.136454,-0.338214,0.068372,0.371503,0.673871,1496.093750
359421,81,3,-1.429197,0.551953,-0.231390,-0.032266,0.149262,-0.018225,0.122059,0.847657,...,0.994058,-0.269558,-0.028525,-1.051387,0.062256,-0.330017,0.141756,0.410057,0.682258,1497.070312
359422,81,3,-1.397744,0.588607,-0.265430,-0.117681,0.184459,-0.048643,0.105742,0.897478,...,1.036175,-0.167436,0.020301,-0.842824,0.396513,-0.121367,0.434557,0.575310,0.912079,1498.046875
359423,81,3,-1.365890,0.568882,-0.244426,-0.090889,0.165881,0.094858,0.101904,0.933569,...,1.104176,-0.241988,-0.101359,-0.783718,0.600151,-0.166676,0.535253,0.521306,0.846202,1499.023438

In [27]:
import os
df.to_csv(os.path.join(r'C:\Users\meghnouh\PycharmProjects\Schizophrenia Detection\all_chans_ERP.csv'))